/*
Copyright 2023 Dagan Poulin, Justice Guillory
   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at
       http://www.apache.org/licenses/LICENSE-2.0
   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/
#ifndef RESULT_LOOKUP_H
#define RESULT_LOOKUP_H

#include "sb-engine.hpp"
#include "./vulkan/vulkan.hpp"

using namespace std;


namespace SBE
{
    string VkResultLookup(VkResult result)
    {
        string returnable = "RESULT_NOT_FOUND";

        #define CONDITION(a,b) returnable = (result==b) ? a : returnable;

        CONDITION("VK_SUCCESS",0);
        CONDITION("VK_NOT_READY",1);
        CONDITION("VK_TIMEOUT",2);
        CONDITION("VK_EVENT_SET",3);
        CONDITION("VK_EVENT_RESET",4);
        CONDITION("VK_INCOMPLETE",5);
        CONDITION("VK_ERROR_OUT_OF_HOST_MEMORY",-1);
        CONDITION("VK_ERROR_OUT_OF_DEVICE_MEMORY",-2);
        CONDITION("VK_ERROR_INITIALIZATION_FAILED",-3);
        CONDITION("VK_ERROR_DEVICE_LOST",-4);
        CONDITION("VK_ERROR_MEMORY_MAP_FAILED",-5);
        CONDITION("VK_ERROR_LAYER_NOT_PRESENT",-6);
        CONDITION("VK_ERROR_EXTENSION_NOT_PRESENT",-7);
        CONDITION("VK_ERROR_FEATURE_NOT_PRESENT",-8);
        CONDITION("VK_ERROR_INCOMPATIBLE_DRIVER",-9);
        CONDITION("VK_ERROR_TOO_MANY_OBJECTS",-10);
        CONDITION("VK_ERROR_FORMAT_NOT_SUPPORTED",-11);
        CONDITION("VK_ERROR_FRAGMENTED_POOL",-12);
        CONDITION("VK_ERROR_UNKNOWN",-13);
        CONDITION("VK_ERROR_OUT_OF_POOL_MEMORY",-1000069000);
        CONDITION("VK_ERROR_INVALID_EXTERNAL_HANDLE",-1000072003);
        CONDITION("VK_ERROR_FRAGMENTATION",-1000161000);
        CONDITION("VK_ERROR_INVALID_OPAQUE_CAPTURE_ADDRESS",-1000257000);
        CONDITION("VK_PIPELINE_COMPILE_REQUIRED",1000297000);
        CONDITION("VK_ERROR_SURFACE_LOST_KHR",-1000000000);
        CONDITION("VK_ERROR_NATIVE_WINDOW_IN_USE_KHR",-1000000001);
        CONDITION("VK_SUBOPTIMAL_KHR",1000001003);
        CONDITION("VK_ERROR_OUT_OF_DATE_KHR",-1000001004);
        CONDITION("VK_ERROR_INCOMPATIBLE_DISPLAY_KHR",-1000003001);
        CONDITION("VK_ERROR_VALIDATION_FAILED_EXT",-1000011001);
        CONDITION("VK_ERROR_INVALID_SHADER_NV",-1000012000);
        CONDITION("VK_ERROR_IMAGE_USAGE_NOT_SUPPORTED_KHR",-1000023000);
        CONDITION("VK_ERROR_VIDEO_PICTURE_LAYOUT_NOT_SUPPORTED_KHR",-1000023001);
        CONDITION("VK_ERROR_VIDEO_PROFILE_OPERATION_NOT_SUPPORTED_KHR",-1000023002);
        CONDITION("VK_ERROR_VIDEO_PROFILE_FORMAT_NOT_SUPPORTED_KHR",-1000023003);
        CONDITION("VK_ERROR_VIDEO_PROFILE_CODEC_NOT_SUPPORTED_KHR",-1000023004);
        CONDITION("VK_ERROR_VIDEO_STD_VERSION_NOT_SUPPORTED_KHR",-1000023005);
        CONDITION("VK_ERROR_INVALID_DRM_FORMAT_MODIFIER_PLANE_LAYOUT_EXT",-1000158000);
        CONDITION("VK_ERROR_NOT_PERMITTED_KHR",-1000174001);
        CONDITION("VK_ERROR_FULL_SCREEN_EXCLUSIVE_MODE_LOST_EXT",-1000255000);
        CONDITION("VK_THREAD_IDLE_KHR",1000268000);
        CONDITION("VK_THREAD_DONE_KHR",1000268001);
        CONDITION("VK_OPERATION_DEFERRED_KHR",1000268002);
        CONDITION("VK_OPERATION_NOT_DEFERRED_KHR",1000268003);
        CONDITION("VK_ERROR_COMPRESSION_EXHAUSTED_EXT",-1000338000);
        CONDITION("VK_ERROR_OUT_OF_POOL_MEMORY_KHR",-1000069000);
        CONDITION("VK_ERROR_INVALID_EXTERNAL_HANDLE_KHR",-1000072003);
        CONDITION("VK_ERROR_FRAGMENTATION_EXT",-1000161000);
        CONDITION("VK_ERROR_NOT_PERMITTED_EXT",-1000174001);
        CONDITION("VK_ERROR_INVALID_DEVICE_ADDRESS_EXT",-1000257000);
        CONDITION("VK_ERROR_INVALID_OPAQUE_CAPTURE_ADDRESS_KHR",-1000257000);
        CONDITION("VK_PIPELINE_COMPILE_REQUIRED_EXT",1000297000);
        CONDITION("VK_ERROR_PIPELINE_COMPILE_REQUIRED_EXT",1000297000);
        CONDITION("VK_RESULT_MAX_ENUM",0x7FFFFFFF);
        
        #undef CONDITION

        return returnable;
    }
}

#endif